export const LevelData: any[] = [
  {
    level: 1,
    era: "Nomadia",
    gdp: 1000000,
    citizenRole: "Digital Nomad",
    citizenLevel: "Novice",
    eraDescription: "Set up your travel base and start your online business.",
    cityDescription:
      "A young entrepreneur travels the world while running a successful online business.",
  },
  {
    level: 2,
    era: "Greenlandia",
    gdp: 2000000,
    citizenRole: "Climate Crusader",
    citizenLevel: "Recruit",
    eraDescription: "Organize your first environmental protest.",
    cityDescription:
      "A teenager leads a local movement to combat climate change.",
  },
  {
    level: 3,
    era: "Esportica",
    gdp: 3000000,
    citizenRole: "E-Sports Star",
    citizenLevel: "Initiate",
    eraDescription: "Train for your first big e-sports tournament.",
    cityDescription: "A gamer rises to fame in the competitive e-sports world.",
  },
  {
    level: 4,
    era: "Techland",
    gdp: 4000000,
    citizenRole: "Tech Innovator",
    citizenLevel: "Apprentice",
    eraDescription: "Develop your first app prototype.",
    cityDescription:
      "A young coder creates an app that goes viral and changes lives.",
  },
  {
    level: 5,
    era: "Influencetopia",
    gdp: 5000000,
    citizenRole: "Social Media Influencer",
    citizenLevel: "Squire",
    eraDescription:
      "Create your social media accounts and start gaining followers.",
    cityDescription: "Navigating the highs and lows of internet fame.",
  },
  {
    level: 6,
    era: "Wellbeingia",
    gdp: 6000000,
    citizenRole: "Mental Health Advocate",
    citizenLevel: "Aspirant",
    eraDescription:
      "Build a support group for students facing mental health issues.",
    cityDescription:
      "A student starts a support group after facing their own struggles.",
  },
  {
    level: 7,
    era: "Virtualia",
    gdp: 7000000,
    citizenRole: "Virtual Reality Adventure",
    citizenLevel: "Acolyte",
    eraDescription:
      "Enter a virtual reality game and complete your first quest.",
    cityDescription: "A group of friends gets trapped in a VR game.",
  },
  {
    level: 8,
    era: "Mysteria",
    gdp: 8000000,
    citizenRole: "Digital Detective",
    citizenLevel: "Neophyte",
    eraDescription: "Solve your first mystery using tech tools.",
    cityDescription: "A teen solves mysteries using their tech skills.",
  },
  {
    level: 9,
    era: "Ecofashionia",
    gdp: 9000000,
    citizenRole: "Sustainable Fashion Designer",
    citizenLevel: "Rookie",
    eraDescription: "Design your first eco-friendly clothing line.",
    cityDescription: "Creating eco-friendly clothing that becomes a trend.",
  },
  {
    level: 10,
    era: "Musiconia",
    gdp: 10000000,
    citizenRole: "Music Streaming Sensation",
    citizenLevel: "Trainee",
    eraDescription:
      "Record and release your first song on streaming platforms.",
    cityDescription: "A musician uses social media to launch their career.",
  },
  {
    level: 11,
    era: "Justiceia",
    gdp: 18000000,
    citizenRole: "Teenage Activist",
    citizenLevel: "Greenhorn",
    eraDescription: "Plan your first social justice campaign.",
    cityDescription: "Fighting for social justice in their community.",
  },
  {
    level: 12,
    era: "AItopia",
    gdp: 27000000,
    citizenRole: "AI Companion",
    citizenLevel: "Fledgling",
    eraDescription: "Program your first AI friend.",
    cityDescription:
      "Exploring the relationship between a teen and their AI friend.",
  },
  {
    level: 13,
    era: "Marsia",
    gdp: 36000000,
    citizenRole: "Space Explorer",
    citizenLevel: "Freshman",
    eraDescription: "Prepare for and embark on a mission to Mars.",
    cityDescription: "Young astronauts on a mission to Mars.",
  },
  {
    level: 14,
    era: "Cybershieldia",
    gdp: 45000000,
    citizenRole: "Cybersecurity Hero",
    citizenLevel: "Newbie",
    eraDescription: "Defend against hackers and cyber threats.",
    cityDescription: "Defending against hackers and cyber threats.",
  },
  {
    level: 15,
    era: "VirtuSchoolia",
    gdp: 54000000,
    citizenRole: "Online Education",
    citizenLevel: "Tenderfoot",
    eraDescription: "Excel in a virtual school setting.",
    cityDescription: "A student excels in a virtual school setting.",
  },
  {
    level: 16,
    era: "Urbanagro",
    gdp: 63000000,
    citizenRole: "Urban Farmer",
    citizenLevel: "Beginner",
    eraDescription: "Grow food in the city and promote sustainable living.",
    cityDescription:
      "Growing food in the city and promoting sustainable living.",
  },
  {
    level: 17,
    era: "Politicia",
    gdp: 72000000,
    citizenRole: "Gen Z Politician",
    citizenLevel: "Amateur",
    eraDescription: "Run for local office to make a difference.",
    cityDescription: "Running for local office to make a difference.",
  },
  {
    level: 18,
    era: "DIYland",
    gdp: 81000000,
    citizenRole: "DIY Creator",
    citizenLevel: "Learner",
    eraDescription: "Build a successful DIY YouTube channel.",
    cityDescription: "Building a successful DIY YouTube channel.",
  },
  {
    level: 19,
    era: "Identia",
    gdp: 90000000,
    citizenRole: "Self-Discovery Journey",
    citizenLevel: "Pupil",
    eraDescription: "Explore your identity in a digital world.",
    cityDescription: "Exploring identity in a digital world.",
  },
  {
    level: 20,
    era: "Friendtopia",
    gdp: 180000000,
    citizenRole: "Virtual Friendship",
    citizenLevel: "Novitiate",
    eraDescription: "Build deep connections online.",
    cityDescription: "Building deep connections online.",
  },
  {
    level: 21,
    era: "Vlogville",
    gdp: 240000000,
    citizenRole: "Family Vlogger",
    citizenLevel: "Proselyte",
    eraDescription:
      "Navigate the challenges of sharing your personal life online.",
    cityDescription:
      "Navigating the challenges of sharing personal life online.",
  },
  {
    level: 22,
    era: "Retreatia",
    gdp: 320000000,
    citizenRole: "Tech-Free Retreat",
    citizenLevel: "Tyro",
    eraDescription: "Find peace away from screens.",
    cityDescription: "Finding peace away from screens.",
  },
  {
    level: 23,
    era: "Crowdland",
    gdp: 400000000,
    citizenRole: "Crowdsourced Project",
    citizenLevel: "Newcomer",
    eraDescription: "Lead a community-driven initiative.",
    cityDescription: "Leading a community-driven initiative.",
  },
  {
    level: 24,
    era: "Diversia",
    gdp: 480000000,
    citizenRole: "Cultural Influencer",
    citizenLevel: "Entrant",
    eraDescription: "Promote diversity and inclusion through social media.",
    cityDescription: "Promoting diversity and inclusion through social media.",
  },
  {
    level: 25,
    era: "Remoteville",
    gdp: 560000000,
    citizenRole: "Remote Worker",
    citizenLevel: "Freshman",
    eraDescription: "Balance work and life while telecommuting.",
    cityDescription: "Balancing work and life while telecommuting.",
  },
  {
    level: 26,
    era: "Guildland",
    gdp: 640000000,
    citizenRole: "Online Gaming Guild",
    citizenLevel: "Junior",
    eraDescription: "Manage a successful online gaming guild.",
    cityDescription: "Managing a successful gaming group.",
  },
  {
    level: 27,
    era: "Festivalia",
    gdp: 720000000,
    citizenRole: "Music Festival Vlogger",
    citizenLevel: "Upstart",
    eraDescription: "Document experiences at music festivals around the world.",
    cityDescription: "Documenting experiences at festivals around the world.",
  },
  {
    level: 28,
    era: "Detoxland",
    gdp: 800000000,
    citizenRole: "Digital Detox",
    citizenLevel: "Starter",
    eraDescription: "Experience the impact of unplugging from digital devices.",
    cityDescription:
      "A story about unplugging and reconnecting with the real world.",
  },
  {
    level: 29,
    era: "Ecommercia",
    gdp: 1600000000,
    citizenRole: "E-commerce Entrepreneur",
    citizenLevel: "Probationary",
    eraDescription: "Start an online store from scratch.",
    cityDescription: "Starting an online store from scratch.",
  },
  {
    level: 30,
    era: "Streamland",
    gdp: 2400000000,
    citizenRole: "Streaming Star",
    citizenLevel: "Provisional",
    eraDescription: "Become a popular streamer on Twitch.",
    cityDescription: "Becoming a popular streamer on Twitch.",
  },
  {
    level: 31,
    era: "Activia",
    gdp: 2800000000,
    citizenRole: "Social Justice Warrior",
    citizenLevel: "Embryonic",
    eraDescription: "Lead social change through online platforms.",
    cityDescription: "Fighting for change on social media.",
  },
  {
    level: 32,
    era: "VirtuConcertia",
    gdp: 3500000000,
    citizenRole: "Virtual Concerts",
    citizenLevel: "Fledgling",
    eraDescription: "Revolutionize the music industry with virtual concerts.",
    cityDescription:
      "Revolutionizing the music industry with online performances.",
  },
  {
    level: 33,
    era: "Kickstartia",
    gdp: 4200000000,
    citizenRole: "Crowdfunding Success",
    citizenLevel: "Incipient",
    eraDescription:
      "Launch a product through a successful crowdfunding campaign.",
    cityDescription:
      "Launching a product through a successful Kickstarter campaign.",
  },
  {
    level: 34,
    era: "Artland",
    gdp: 4900000000,
    citizenRole: "Digital Art Revolution",
    citizenLevel: "Nascent",
    eraDescription: "Create and sell digital artwork.",
    cityDescription: "Creating and selling digital artwork.",
  },
  {
    level: 35,
    era: "Podcastria",
    gdp: 5600000000,
    citizenRole: "Gen Z Podcaster",
    citizenLevel: "Untested",
    eraDescription: "Share stories and interviews on a popular podcast.",
    cityDescription: "Sharing stories and interviews on a popular podcast.",
  },
  {
    level: 36,
    era: "Privatia",
    gdp: 6300000000,
    citizenRole: "Internet Fame and Privacy",
    citizenLevel: "Unseasoned",
    eraDescription: "Balance your public persona and personal privacy online.",
    cityDescription: "Balancing public persona and personal life.",
  },
  {
    level: 37,
    era: "Tutorville",
    gdp: 7000000000,
    citizenRole: "Online Tutor",
    citizenLevel: "Untried",
    eraDescription: "Help others learn through virtual lessons.",
    cityDescription: "Helping others learn through virtual lessons.",
  },
  {
    level: 38,
    era: "NomaFamilyia",
    gdp: 14000000000,
    citizenRole: "Digital Nomad Family",
    citizenLevel: "Verdant",
    eraDescription: "Travel the world with your family while working remotely.",
    cityDescription:
      "Traveling the world with a family while working remotely.",
  },
  {
    level: 39,
    era: "Fitlandia",
    gdp: 21000000000,
    citizenRole: "Fitness Influencer",
    citizenLevel: "Green",
    eraDescription: "Promote health and wellness through social media.",
    cityDescription: "Promoting health and wellness through social media.",
  },
  {
    level: 40,
    era: "Fashionia",
    gdp: 28000000000,
    citizenRole: "Virtual Fashion Shows",
    citizenLevel: "Raw",
    eraDescription: "Create and participate in digital fashion events.",
    cityDescription: "Creating and participating in digital fashion events.",
  },
  {
    level: 41,
    era: "ZeroWasteia",
    gdp: 30000000000,
    citizenRole: "Zero Waste Lifestyle",
    citizenLevel: "Callow",
    eraDescription: "Live sustainably and share your journey online.",
    cityDescription: "Living sustainably and sharing the journey online.",
  },
  {
    level: 42,
    era: "CryptoLand",
    gdp: 36000000000,
    citizenRole: "Cryptocurrency Trader",
    citizenLevel: "Cub",
    eraDescription: "Navigate the highs and lows of digital currency trading.",
    cityDescription: "Navigating the highs and lows of digital currency.",
  },
  {
    level: 43,
    era: "Augmentia",
    gdp: 42000000000,
    citizenRole: "Augmented Reality Innovator",
    citizenLevel: "Cadet",
    eraDescription: "Create augmented reality experiences.",
    cityDescription: "Creating AR experiences.",
  },
  {
    level: 44,
    era: "SmartHomia",
    gdp: 48000000000,
    citizenRole: "Smart Home Designer",
    citizenLevel: "Padawan",
    eraDescription: "Develop intelligent home solutions.",
    cityDescription: "Developing intelligent home solutions.",
  },
  {
    level: 45,
    era: "GamerGirlia",
    gdp: 54000000000,
    citizenRole: "Gamer Girl",
    citizenLevel: "Journeyman",
    eraDescription: "Break stereotypes in the gaming community.",
    cityDescription: "Breaking stereotypes in the gaming community.",
  },
  {
    level: 46,
    era: "InternLand",
    gdp: 60000000000,
    citizenRole: "Virtual Internship",
    citizenLevel: "Yeoman",
    eraDescription: "Gain experience through remote internships.",
    cityDescription: "Gaining experience through remote internships.",
  },
  {
    level: 47,
    era: "Detoxia",
    gdp: 120000000000,
    citizenRole: "Social Media Detox",
    citizenLevel: "Artisan",
    eraDescription:
      "Experience the impact of taking a break from social platforms.",
    cityDescription: "The impact of taking a break from social platforms.",
  },
  {
    level: 48,
    era: "Mindland",
    gdp: 180000000000,
    citizenRole: "Mental Health on Social Media",
    citizenLevel: "Adept",
    eraDescription: "Promote mental health and coping strategies online.",
    cityDescription: "Promoting wellness and coping strategies online.",
  },
  {
    level: 49,
    era: "Petinfluia",
    gdp: 240000000000,
    citizenRole: "Pet Influencer",
    citizenLevel: "Proficient",
    eraDescription: "Manage a popular pet's social media account.",
    cityDescription: "Managing a popular pet's social media account.",
  },
  {
    level: 50,
    era: "Storyland",
    gdp: 300000000000,
    citizenRole: "Digital Storytelling",
    citizenLevel: "Skilled",
    eraDescription: "Use technology to tell compelling stories.",
    cityDescription: "Using technology to tell compelling stories.",
  },
  {
    level: 51,
    era: "VRTravelia",
    gdp: 330000000000,
    citizenRole: "Virtual Travel Vlogger",
    citizenLevel: "Capable",
    eraDescription: "Explore the world through virtual reality.",
    cityDescription: "Exploring the world through VR.",
  },
  {
    level: 52,
    era: "Startupia",
    gdp: 385000000000,
    citizenRole: "Tech Start-up",
    citizenLevel: "Experienced",
    eraDescription: "Launch a new tech company.",
    cityDescription: "Launching a new tech company.",
  },
  {
    level: 53,
    era: "Activistan",
    gdp: 440000000000,
    citizenRole: "Online Activism",
    citizenLevel: "Veteran",
    eraDescription: "Lead change from behind a screen.",
    cityDescription: "Leading change from behind a screen.",
  },
  {
    level: 54,
    era: "Photographia",
    gdp: 495000000000,
    citizenRole: "Digital Photography",
    citizenLevel: "Seasoned",
    eraDescription: "Capture and share stunning digital images.",
    cityDescription: "Capturing and sharing stunning images.",
  },
  {
    level: 55,
    era: "Codeville",
    gdp: 550000000000,
    citizenRole: "Coding Bootcamp",
    citizenLevel: "Practiced",
    eraDescription: "Learn to code and land a dream job.",
    cityDescription: "Learning to code and landing a dream job.",
  },
  {
    level: 56,
    era: "Impactia",
    gdp: 1100000000000,
    citizenRole: "Social Impact Business",
    citizenLevel: "Versed",
    eraDescription: "Start a business that makes a social impact.",
    cityDescription: "Starting a company that makes a difference.",
  },
  {
    level: 57,
    era: "TherapVRia",
    gdp: 1650000000000,
    citizenRole: "Virtual Reality Therapy",
    citizenLevel: "Qualified",
    eraDescription: "Use VR for mental health treatment.",
    cityDescription: "Using VR for mental health treatment.",
  },
  {
    level: 58,
    era: "Innovatia",
    gdp: 2200000000000,
    citizenRole: "Crowdsourced Innovation",
    citizenLevel: "Credentialed",
    eraDescription: "Develop new products with community input.",
    cityDescription: "Developing new products with input from the community.",
  },
  {
    level: 59,
    era: "Investopia",
    gdp: 2750000000000,
    citizenRole: "Gen Z Investor",
    citizenLevel: "Accomplished",
    eraDescription: "Navigate the stock market and investments.",
    cityDescription: "Navigating the stock market and investments.",
  },
  {
    level: 60,
    era: "Marketia",
    gdp: 3300000000000,
    citizenRole: "Digital Marketing Guru",
    citizenLevel: "Masterly",
    eraDescription: "Master digital marketing.",
    cityDescription: "Mastering online advertising.",
  },
  {
    level: 61,
    era: "Brandville",
    gdp: 3500000000000,
    citizenRole: "Social Media Manager",
    citizenLevel: "Consummate",
    eraDescription: "Build brands through strategic online presence.",
    cityDescription: "Building brands through strategic online presence.",
  },
  {
    level: 62,
    era: "Travelogica",
    gdp: 4000000000000,
    citizenRole: "Travel Blogger",
    citizenLevel: "Exceptional",
    eraDescription: "Document your travels and earn a living online.",
    cityDescription: "Documenting travels and earning a living online.",
  },
  {
    level: 63,
    era: "FitAppia",
    gdp: 4500000000000,
    citizenRole: "Fitness App Developer",
    citizenLevel: "Illustrious",
    eraDescription: "Create an app that promotes health and fitness.",
    cityDescription: "Creating an app that promotes health and fitness.",
  },
  {
    level: 64,
    era: "TechGoodia",
    gdp: 50000000000000,
    citizenRole: "Tech for Good",
    citizenLevel: "Distinguished",
    eraDescription: "Use technology to solve social issues.",
    cityDescription: "Using technology to solve social issues.",
  },
  {
    level: 65,
    era: "Streamtopia",
    gdp: 100000000000000,
    citizenRole: "Streaming Gamer",
    citizenLevel: "Preeminent",
    eraDescription: "Build a following through live gaming.",
    cityDescription: "Building a following through live gaming.",
  },
  {
    level: 66,
    era: "NomaChallengeia",
    gdp: 150000000000000,
    citizenRole: "Digital Nomad Challenger",
    citizenLevel: "Supreme",
    eraDescription: "Experience the ups and downs of a nomadic lifestyle.",
    cityDescription: "The ups and downs of a nomadic lifestyle.",
  },
  {
    level: 67,
    era: "Ebookia",
    gdp: 200000000000000,
    citizenRole: "E-book Author",
    citizenLevel: "Transcendent",
    eraDescription: "Write and publish online books.",
    cityDescription: "Writing and publishing online books.",
  },
  {
    level: 68,
    era: "VRFilmland",
    gdp: 250000000000000,
    citizenRole: "Virtual Reality Filmmaker",
    citizenLevel: "Paramount",
    eraDescription: "Create immersive films.",
    cityDescription: "Creating immersive films.",
  },
  {
    level: 69,
    era: "Communityland",
    gdp: 300000000000000,
    citizenRole: "Online Community Builder",
    citizenLevel: "Peerless",
    eraDescription: "Create a supportive online space.",
    cityDescription: "Creating a supportive online space.",
  },
  {
    level: 70,
    era: "CryptoEduca",
    gdp: 350000000000000,
    citizenRole: "Cryptocurrency Educator",
    citizenLevel: "Unrivaled",
    eraDescription: "Teach others about digital currency.",
    cityDescription: "Teaching others about digital currency.",
  },
  {
    level: 71,
    era: "EcoTechia",
    gdp: 376000000000000,
    citizenRole: "Eco-Friendly Tech",
    citizenLevel: "Inimitable",
    eraDescription: "Develop sustainable technology solutions.",
    cityDescription: "Developing sustainable technology solutions.",
  },
  {
    level: 72,
    era: "FitCoachia",
    gdp: 423000000000000,
    citizenRole: "Digital Fitness Coach",
    citizenLevel: "Matchless",
    eraDescription: "Offer virtual fitness training.",
    cityDescription: "Offering virtual fitness training.",
  },
  {
    level: 73,
    era: "Wearableland",
    gdp: 470000000000000,
    citizenRole: "Smart Wearables Designer",
    citizenLevel: "Unequaled",
    eraDescription: "Create the next big thing in smart wearables.",
    cityDescription: "Creating the next big thing in wearables.",
  },
  {
    level: 74,
    era: "TeamRemoteia",
    gdp: 940000000000000,
    citizenRole: "Remote Team Leader",
    citizenLevel: "Unsurpassed",
    eraDescription: "Manage a remote team effectively.",
    cityDescription: "Managing a team from afar.",
  },
  {
    level: 75,
    era: "TherapyOnlineia",
    gdp: 1410000000000000,
    citizenRole: "Online Therapy",
    citizenLevel: "Unexcelled",
    eraDescription: "Provide mental health support virtually.",
    cityDescription: "Providing mental health support virtually.",
  },
  {
    level: 76,
    era: "MusicCollabia",
    gdp: 1880000000000000,
    citizenRole: "Music Collaboration Online",
    citizenLevel: "Virtuoso",
    eraDescription: "Create music with artists from around the world online.",
    cityDescription: "Creating music with artists from around the world.",
  },
  {
    level: 77,
    era: "StreamCritia",
    gdp: 2350000000000000,
    citizenRole: "Streaming Service Critic",
    citizenLevel: "Mastermind",
    eraDescription: "Review and analyze streaming content.",
    cityDescription: "Reviewing and analyzing streaming content.",
  },
  {
    level: 78,
    era: "Privacyland",
    gdp: 2820000000000000,
    citizenRole: "Digital Privacy Advocate",
    citizenLevel: "Maestro",
    eraDescription: "Protect personal data in the digital age.",
    cityDescription: "Protecting personal data in the digital age.",
  },
  {
    level: 79,
    era: "EcoInnovia",
    gdp: 3290000000000000,
    citizenRole: "Eco-Innovator",
    citizenLevel: "Grandmaster",
    eraDescription: "Develop green technology.",
    cityDescription: "Developing green technology.",
  },
  {
    level: 80,
    era: "Crowdcontentia",
    gdp: 3760000000000000,
    citizenRole: "Crowdsourced Content",
    citizenLevel: "Luminary",
    eraDescription: "Create media with audience participation.",
    cityDescription: "Creating media with audience participation.",
  },
  {
    level: 81,
    era: "StartUpTopia",
    gdp: 4050000000000000,
    citizenRole: "Gen Z Entrepreneur",
    citizenLevel: "Savant",
    eraDescription: "Launch a successful start-up.",
    cityDescription: "Launching a successful start-up.",
  },
  {
    level: 82,
    era: "Minimalistica",
    gdp: 4500000000000000,
    citizenRole: "Digital Minimalism",
    citizenLevel: "Prodigy",
    eraDescription: "Embrace a simpler, tech-reduced lifestyle.",
    cityDescription: "Embracing a simpler, tech-reduced lifestyle.",
  },
  {
    level: 83,
    era: "ArtGalleryia",
    gdp: 9000000000000000,
    citizenRole: "Online Art Gallery",
    citizenLevel: "Genius",
    eraDescription: "Showcase and sell digital art.",
    cityDescription: "Showcasing and selling digital art.",
  },
  {
    level: 84,
    era: "Activismia",
    gdp: 13500000000000000,
    citizenRole: "Social Media Activism",
    citizenLevel: "Maven",
    eraDescription: "Lead change through online campaigns.",
    cityDescription: "Leading change through online campaigns.",
  },
  {
    level: 85,
    era: "VRGameLand",
    gdp: 18000000000000000,
    citizenRole: "Virtual Reality Gaming",
    citizenLevel: "Sage",
    eraDescription: "Develop or master VR games.",
    cityDescription: "Developing or mastering VR games.",
  },
  {
    level: 86,
    era: "TeleMedicia",
    gdp: 22500000000000000,
    citizenRole: "Telemedicine Pioneer",
    citizenLevel: "Polymath",
    eraDescription: "Innovate in remote healthcare.",
    cityDescription: "Innovating in remote healthcare.",
  },
  {
    level: 87,
    era: "MusicProdia",
    gdp: 27000000000000000,
    citizenRole: "Online Music Producer",
    citizenLevel: "Erudite",
    eraDescription: "Create and distribute music digitally.",
    cityDescription: "Creating and distributing music digitally.",
  },
  {
    level: 88,
    era: "RemoteAdvocateia",
    gdp: 31500000000000000,
    citizenRole: "Remote Work Advocate",
    citizenLevel: "Pundit",
    eraDescription: "Promote the benefits of telecommuting.",
    cityDescription: "Promoting the benefits of telecommuting.",
  },
  {
    level: 89,
    era: "EcoInfluencia",
    gdp: 36000000000000000,
    citizenRole: "Eco-Influencer",
    citizenLevel: "Orator",
    eraDescription: "Use social media to promote environmental awareness.",
    cityDescription: "Using social media to promote environmental awareness.",
  },
  {
    level: 90,
    era: "Collabora",
    gdp: 40500000000000000,
    citizenRole: "Virtual Collaboration",
    citizenLevel: "Scholar",
    eraDescription: "Work with a global team on digital projects.",
    cityDescription: "Working with a global team on digital projects.",
  },
  {
    level: 91,
    era: "EcomInnovia",
    gdp: 42000000000000000,
    citizenRole: "E-commerce Innovator",
    citizenLevel: "Litterateur",
    eraDescription: "Revolutionize online shopping.",
    cityDescription: "Revolutionizing online shopping.",
  },
  {
    level: 92,
    era: "EduPlatformia",
    gdp: 84000000000000000,
    citizenRole: "Digital Education Platform",
    citizenLevel: "Philosopher",
    eraDescription: "Develop new ways to learn online.",
    cityDescription: "Developing new ways to learn online.",
  },
  {
    level: 93,
    era: "Strategia",
    gdp: 126000000000000000,
    citizenRole: "Social Media Strategist",
    citizenLevel: "Visionary",
    eraDescription: "Craft effective online marketing strategies.",
    cityDescription: "Crafting effective online marketing strategies.",
  },
  {
    level: 94,
    era: "EventPlania",
    gdp: 168000000000000000,
    citizenRole: "Virtual Event Planner",
    citizenLevel: "Oracle",
    eraDescription: "Organize successful virtual events.",
    cityDescription: "Organizing successful online events.",
  },
  {
    level: 95,
    era: "GameEntrepreneuria",
    gdp: 210000000000000000,
    citizenRole: "Online Gaming Entrepreneur",
    citizenLevel: "Prophet",
    eraDescription: "Build a business around gaming.",
    cityDescription: "Building a business around gaming.",
  },
  {
    level: 96,
    era: "HealthTechia",
    gdp: 252000000000000000,
    citizenRole: "Digital Health Innovator",
    citizenLevel: "Seer",
    eraDescription: "Create tech solutions for healthcare.",
    cityDescription: "Creating tech solutions for healthcare.",
  },
  {
    level: 97,
    era: "CryptoInfluencia",
    gdp: 294000000000000000,
    citizenRole: "Cryptocurrency Influencer",
    citizenLevel: "Augur",
    eraDescription: "Share insights and advice on digital currency.",
    cityDescription: "Sharing insights and advice on digital currency.",
  },
  {
    level: 98,
    era: "RemoteFitnessia",
    gdp: 336000000000000000,
    citizenRole: "Remote Fitness Trainer",
    citizenLevel: "Soothsayer",
    eraDescription: "Offer workout plans and coaching online.",
    cityDescription: "Offering workout plans and coaching online.",
  },
  {
    level: 99,
    era: "InvestTopia",
    gdp: 378000000000000000,
    citizenRole: "Gen Z Investor",
    citizenLevel: "Diviner",
    eraDescription: "Start young in the world of investments.",
    cityDescription: "Starting young in the world of investments.",
  },
  {
    level: 100,
    era: "VirtuClassia",
    gdp: 420000000000000000,
    citizenRole: "Virtual Classroom Creator",
    citizenLevel: "Clairvoyant",
    eraDescription: "Develop engaging online learning environments.",
    cityDescription: "Developing engaging online learning environments",
  },
];
